python test.py --prob cross_9 --algo 0 --runs 10 --num-amrs 20  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_9 --algo 0 --runs 10 --num-amrs 30  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_9 --algo 0 --runs 10 --num-amrs 40  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_520 --algo 0 --runs 10 --num-amrs 500 --max-arm-h 20 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_520 --algo 0 --runs 10 --num-amrs 750 --max-arm-h 20 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_520 --algo 0 --runs 10 --num-amrs 1000 --max-arm-h 20 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_3030 --algo 0 --runs 10 --num-amrs 500 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_3030 --algo 0 --runs 10 --num-amrs 750 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt
python test.py --prob cross_3030 --algo 0 --runs 10 --num-amrs 1000 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_mlp_policy.pt