python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 3  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 4  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 5  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 6  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 7  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 8  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 9  --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 10 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 11 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 12 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 13 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 14 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt
python test.py --prob cross_1 --algo 0 --runs 10 --num-amrs 15 --max-arm-h 5 --max-arm-v 5 --max-steps 10000 --use-rl --model-path checkpoint/final_policy.pt